### ISSUE TITLE
[typescript-sdk] queryArgs does not define parameters containing dots

### ISSUE THREAD

**Issue by lenkan** [commercetools/nodejs#1469]
### Description

Query args containing `.`'s are missing in the generated types.

See specification for product projection search [here](https://github.com/commercetools/commercetools-api-reference/blob/5e8494ab13d84c6fe132c2a4e8f046a3689a0ca5/resources/product-projections-search.raml#L29):

```yaml
....
 queryParameters:
    fuzzy?:
      type: boolean
      description: Whether to apply fuzzy search on the text to analyze.
    fuzzyLevel?:
      type: number
      description: |
        Provide explicitly the fuzzy level desired if fuzzy is enabled. This value can not be higher than the one
        chosen by the platform by default.
    staged?:
      type: boolean
      description: Whether to query for the current or staged projections.
    filter?:
      type: string
    filter.facets?:
      type: string
    filter.query?:
      type: string
    facet?:
      type: string
.....
```

It contains two query parameters (`filter.query` and `filter.facets`) that are not present in the generated types [here](https://github.com/commercetools/nodejs/blob/70e7ec6ef7d6419952ad924a43298532b1facc9b/packages/typescript-sdk/src/generated/client/search/by-project-key-product-projections-search-request-builder.ts#L38)

```typescript
 public get(methodArgs?: {
    queryArgs?: {
      fuzzy?: boolean | boolean[]
      fuzzyLevel?: number | number[]
      staged?: boolean | boolean[]
      filter?: string | string[]
      facets?: string | string[]
      query?: string | string[]
      facet?: string | string[]
      text?: string | string[]
      sort?: string | string[]
      limit?: number | number[]
      offset?: number | number[]
      withTotal?: boolean | boolean[]
      priceCurrency?: string | string[]
      priceCountry?: string | string[]
      priceCustomerGroup?: string | string[]
      priceChannel?: string | string[]
      expand?: string | string[]
    }
    headers?: {
      [key: string]: string
    }
  }): ApiRequest<ProductProjectionPagedSearchResponse> { ... }
```

### Possible solution

I'm not familiar with kotlin, but it looks like some type of filtering is being applied [here](https://github.com/vrapio/rmf-codegen/blob/2bcc5e21d8f917fa9ddf24c68e430d95fd11f784/languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/RequestBuilder.kt#L112)

```
                    var queryParamsArg = ""
                    var bodies = ""
                    if (!it.queryParameters.isEmpty()) {
                        val allQueryParamsOptional = it.queryParameters.map { !it.required }.reduce(Boolean::and)
                        queryParamsArg =
                                """|queryArgs${if (allQueryParamsOptional) "?" else ""}: {
                            |   <${it.queryParameters.map { "'${it.name.tsRemoveRegexp()}'${if (it.required) "" else "?"}: ${it.type.toVrapType().simpleTSName()} | ${it.type.toVrapType().simpleTSName()}[]" }.joinToString(separator = "\n")}>
                            |},""".trimMargin()
                    }
```

I see that the `tsRemoveRegexp` is doing something with strings that contains `.`'s.

```
    if (this.contains(".")) {
        val index = this.indexOf(".")
        return this.substring(index + 1, this.length)
    }
```

### Expected Behavior

I expect that the `queryArgs` type definition should contain all query parameters for the operation.
